/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_dwmblocks.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_statuscmd.c"
#include "bar_tagpreview.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_systray.c"

/* Other patches */
#include "attachx.c"
#include "autostart.c"
#include "cfacts.c"
#include "cyclelayouts.c"
#include "dragcfact.c"
#include "fullscreen.c"
#include "movestack.c"
#include "pertag.c"
#include "placemouse.c"
#include "push.c"
#include "scratchpad.c"
#include "shift.c"
#include "shiftboth.c"
#include "shiftview.c"
#include "swallow.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "dragmfact.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_centeredmaster.c"
#include "layout_columns.c"
#include "layout_monocle.c"

